version: '{build}'
image: Visual Studio 2017
configuration: Release
before_build:
- ps: nuget restore Bar.sln
build:
  project: Bar.sln
  verbosity: minimal
artifacts:
- path: Bar\bin\Release\Bar.*.nupkg
only_commits:
 files:
   - Bar/
   - BarTests/
   - Bar.sln
   - bar_appveyor.yml