version: '{build}'
image: Visual Studio 2017
configuration: Release
only_commits:
 files:
   - Foo/
   - FooTests/
   - Foo.sln
   - foo_appveyor.yml
before_build:
- ps: >-
    $release_notes = "$env:appveyor_repo_commit_message


    $env:appveyor_repo_commit_message_extended".TrimEnd()


    $file = "Foo\Foo.csproj"


    $doc = [xml](Get-Content $file)


    $package_release_notes = $doc.SelectSingleNode("/Project/PropertyGroup/PackageReleaseNotes")


    $package_release_notes.InnerText = $release_notes


    $doc.Save((get-item $file))


    $package_id = $doc.SelectSingleNode("/Project/PropertyGroup/PackageId").InnerText

    $package_version = $doc.SelectSingleNode("/Project/PropertyGroup/PackageVersion").InnerText


    $package_tag = "$package_id.$package_version"


    Set-AppveyorBuildVariable -Name "release_notes" -Value $release_notes

    Set-AppveyorBuildVariable -Name "package_tag" -Value $package_tag


    "Release notes: $release_notes"

    "Package tag: $package_tag"


    nuget restore Foo.sln
build:
  project: Foo.sln
  verbosity: minimal
artifacts:
- path: Foo\bin\Release\Foo.*.nupkg
deploy:
- provider: GitHub
  description: $(release_notes)
  tag: $(appveyor_repo_tag_name)
  release: $(appveyor_repo_tag_name)
  auth_token:
    secure: yjDw1QLeuxM3Wvq9ZEJIB8JaEK/L2e7MhwrKicm3/SBh0FwbAEb3Fpg82h0fFALU
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: $(package_tag)
