version: '{build}'
image: Visual Studio 2017
configuration: Release
before_build:
- ps: nuget restore Foo.sln
build:
  project: Foo.sln
  verbosity: minimal
artifacts:
- path: Foo\bin\Release\Foo.*.nupkg
only_commits:
 files:
   - Foo/
   - FooTests/
   - Foo.sln
   - foo_appveyor.yml