version: '{build}.0.0-ci'
image: Visual Studio 2017
configuration: Release
only_commits:
 files:
   - Foo/
   - FooTests/
   - Foo.sln
   - foo_appveyor.yml
before_build:
   - ps: $sln_path = "Foo.sln"
   - ps: $csproj_path = "Foo\Foo.csproj"
   - ps: 
   - ps: $package_release_notes = "$Env:appveyor_repo_commit_message`n`n$Env:appveyor_repo_commit_message_extended".Replace("\n", "`n").TrimEnd()
   - ps: 
   - ps: $csproj = [xml](Get-Content $csproj_path)
   - ps: 
   - ps: $package_version_node = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageVersion")
   - ps:
   - ps: $package_id = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageId").InnerText
   - ps: $package_version = $package_version_node.InnerText
   - ps: $package_tag = "$package_id.$package_version"
   - ps: 
   - ps: If ($Env:appveyor_repo_tag -eq "true" -AND $Env:appveyor_repo_tag_name -eq $package_tag) {
           Set-AppveyorBuildVariable -Name "version" -Value $package_version
           Set-AppveyorBuildVariable -Name "package_tag" -Value $package_tag
         } else {
           $package_version_node.InnerText = "$Env:version"
         }
   - ps: 
   - ps: $package_release_notes_node = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageReleaseNotes")
   - ps: $package_release_notes_node.InnerText = $package_release_notes
   - ps: 
   - ps: $csproj.Save((Get-Item $csproj_path))
   - ps: 
   - ps: nuget restore $sln_path
build:
  project: Foo.sln
  verbosity: minimal
artifacts:
- path: '**/Foo.*.nupkg'
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: $(appveyor_repo_commit_message)
  description: $(appveyor_repo_commit_message_extended)
  auth_token:
    secure: yjDw1QLeuxM3Wvq9ZEJIB8JaEK/L2e7MhwrKicm3/SBh0FwbAEb3Fpg82h0fFALU
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: $(package_tag)
notifications:
- provider: Email
  to:
  - brianfriesen@quickenloans.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
